on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Run Linter and Tests
jobs:

  lint:
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Run tests
        run: go test -v ./...
